name: Generate and Deploy Static Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.12.197

      - name: Ensure build.sh is executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh
